apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zachseifts/dashboard.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dashboard-dev
