apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: skireports-mountain
resources:
 - namespace.yaml
 - homer.yaml
configMapGenerator:
  - name: homer-config
    files:
      - homer-config
commonLabels:
  env: prod
